name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd infra && terraform init

      - name: Terraform Validate
        run: cd infra && terraform validate

      - name: Terraform Plan
        run: cd infra && terraform plan

      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve